'use client';

import { useState } from 'react';
import { codexApi } from '@/lib/codex-api';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';

type PullRequestPanelProps = {
  taskId: string;
  branch?: string | null;
  existingPr?: {
    id: string;
    status: string;
    title: string;
    body: string;
    url?: string | null;
  } | null;
  onRefresh: () => Promise<void> | void;
};

export function PullRequestPanel({ taskId, branch, existingPr, onRefresh }: PullRequestPanelProps) {
  const [title, setTitle] = useState(existingPr?.title || `feat(codex): task ${taskId.slice(0, 8)}`);
  const [body, setBody] = useState(existingPr?.body || '## Summary\n\n- generated by codex cloud task');
  const [draft, setDraft] = useState(existingPr?.status === 'draft');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  return (
    <section className="rounded-[var(--radius-2xl)] border border-[var(--border)] bg-[rgba(8,17,31,0.84)] p-4">
      <h2 className="text-sm font-semibold uppercase tracking-[0.14em] text-[var(--subtle-foreground)]">Pull Request</h2>
      <p className="mt-1 text-xs text-[var(--muted-foreground)]">Branch: {branch || `codex/${taskId}`}</p>
      {existingPr?.url && (
        <a
          href={existingPr.url}
          target="_blank"
          rel="noreferrer"
          className="mt-2 inline-flex text-xs text-[var(--brand-primary)] underline underline-offset-4"
        >
          Open existing PR
        </a>
      )}
      <div className="mt-3 space-y-3">
        <label className="space-y-1">
          <span className="text-xs uppercase tracking-[0.14em] text-[var(--subtle-foreground)]">Title</span>
          <Input value={title} onChange={(event) => setTitle(event.target.value)} />
        </label>
        <label className="space-y-1">
          <span className="text-xs uppercase tracking-[0.14em] text-[var(--subtle-foreground)]">Body</span>
          <Textarea rows={8} value={body} onChange={(event) => setBody(event.target.value)} />
        </label>
        <label className="inline-flex items-center gap-2 text-sm text-[var(--muted-foreground)]">
          <input type="checkbox" checked={draft} onChange={(event) => setDraft(event.target.checked)} />
          Draft
        </label>
      </div>
      <div className="mt-4 flex flex-wrap gap-2">
        <Button
          onClick={async () => {
            setLoading(true);
            setError(null);
            try {
              if (existingPr?.id) {
                await codexApi.updateTaskPr(taskId, existingPr.id, {
                  title,
                  body,
                  status: draft ? 'draft' : 'open',
                });
              } else {
                await codexApi.createTaskPr(taskId, { title, body, draft });
              }
              await onRefresh();
            } catch (err) {
              setError(err instanceof Error ? err.message : 'Falha ao salvar PR');
            } finally {
              setLoading(false);
            }
          }}
          disabled={loading}
        >
          {loading ? 'Saving...' : existingPr?.id ? 'Update PR' : 'Create PR'}
        </Button>
      </div>
      {error && <p className="mt-2 text-sm text-[var(--destructive)]">{error}</p>}
    </section>
  );
}

